//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryManagementSystem_DataLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manage()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public int SkillID { get; set; }
        public decimal SalaryAmount { get; set; }
        public string ArrivalDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Skill Skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
