//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryManagementSystem_DataLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public string PayDate { get; set; }
        public decimal Amount { get; set; }
        public int ManageID { get; set; }
        public string Description { get; set; }
    
        public virtual Manage Manage { get; set; }
    }
}
